name: Rodar Selenium Diário

on:
  schedule:
    - cron: '0 12 * * *'  # Roda todo dia às 12:00 UTC (9:00 da manhã no Brasil, horário de Brasília normal)
  workflow_dispatch:  # Permite rodar manualmente também pelo botão "Run Workflow"

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Usa Python 3.11

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Rodar script
      env:
        SUPERBET_USERNAME: ${{ secrets.SUPERBET_USERNAME }}
        SUPERBET_PASSWORD: ${{ secrets.SUPERBET_PASSWORD }}
      run: |
        python seu_script.py

    - name: Upload de screenshots se erro
      if: failure()  # Só executa se o job falhar
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshots
        path: '*.png'
