name: Automação Selenium

on:
  workflow_dispatch:  # Permite rodar manualmente
  schedule:
    - cron: '0 3 * * *'  # Agenda para rodar às 3h UTC todo dia

jobs:
  executar-script:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: choco install googlechrome -y

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Executar Script Selenium
        run: python auto_aposta.py
