name: Automação Selenium

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  executar-script:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: choco install googlechrome

      - name: Baixar ChromeDriver compatível
        run: |
          $chrome_version = (Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.ProductVersion
          $major_version = $chrome_version.Split('.')[0]
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$major_version" -OutFile latest.txt
          $chromedriver_version = Get-Content latest.txt
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$chromedriver_version/chromedriver_win32.zip" -OutFile chromedriver.zip
          Expand-Archive chromedriver.zip -DestinationPath .
          $env:Path += ";$PWD"
      
      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar Script
        run: python auto_aposta.py
